import { useState } from "react";
import { useLocation, useRoute } from "wouter";
import { useQueryClient } from "@tanstack/react-query";
import { Layout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { getGetAssessmentPackageVersionQueryKey, getGetAssessmentQueryKey, getListAssessmentsQueryKey, getListAssessmentPackagePublicationHistoryQueryKey, useCreateAssessmentPackageVersion, useGetAssessment, useGetAssessmentPackageVersion, useListAssessmentPackagePublicationHistory, usePublishAssessmentPackageVersionToRoleplayX, useValidateAssessmentPackageVersion, type AssessmentPackageVersionCreateInput } from "@workspace/api-client-react";
import { useToast } from "@/hooks/use-toast";
import { CheckCircle2, Loader2, PlusCircle, Send, ShieldAlert } from "lucide-react";
import { AssessmentVersionForm } from "./assessment-version-form";

export default function AssessmentDetail() {
  const [, params] = useRoute("/assessments/:id");
  const [, setLocation] = useLocation();
  const id = params?.id ?? "";
  const version = Number(new URLSearchParams(window.location.search).get("version") ?? "1");
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const [validation, setValidation] = useState<boolean | null>(null);
  const [diagnostics, setDiagnostics] = useState<{ path: string; message: string }[]>([]);
  const [publishOpen, setPublishOpen] = useState(false);
  const [newVersionOpen, setNewVersionOpen] = useState(false);
  const [organizationId, setOrganizationId] = useState("");
  const [category, setCategory] = useState("");
  const [publishResult, setPublishResult] = useState<{ status: string; errorCategory?: string; response?: Record<string, unknown> } | null>(null);
  const assessmentDetail = useGetAssessment(id, { query: { enabled: !!id, queryKey: getGetAssessmentQueryKey(id) } });
  const packageQuery = useGetAssessmentPackageVersion(id, version, { query: { enabled: !!id && Number.isFinite(version), queryKey: getGetAssessmentPackageVersionQueryKey(id, version) } });
  const latestVersion = Number(assessmentDetail.data?.currentVersion ?? version);
  const latestPackageQuery = useGetAssessmentPackageVersion(id, latestVersion, { query: { enabled: !!id && Number.isFinite(latestVersion), queryKey: getGetAssessmentPackageVersionQueryKey(id, latestVersion) } });
  const historyQuery = useListAssessmentPackagePublicationHistory(id, { query: { enabled: !!id, queryKey: getListAssessmentPackagePublicationHistoryQueryKey(id) } });
  const validate = useValidateAssessmentPackageVersion();
  const publish = usePublishAssessmentPackageVersionToRoleplayX();
  const createVersion = useCreateAssessmentPackageVersion();
  const runValidation = () => validate.mutate({ id, version }, { onSuccess: (report) => { setValidation(report.valid); setDiagnostics(report.diagnostics); queryClient.invalidateQueries({ queryKey: getGetAssessmentQueryKey(id) }); queryClient.invalidateQueries({ queryKey: getGetAssessmentPackageVersionQueryKey(id, version) }); queryClient.invalidateQueries({ queryKey: getListAssessmentsQueryKey() }); toast({ title: report.valid ? "검증을 통과했습니다" : "검증 실패", description: report.valid ? "RoleplayX 발행을 진행할 수 있습니다." : report.diagnostics.map((d) => `${d.path}: ${d.message}`).join(" · ") }); }, onError: (error) => toast({ variant: "destructive", title: "검증을 실행하지 못했습니다", description: error.message }) });
  const runPublish = () => publish.mutate({ id, version, data: { organizationId, category } }, { onSuccess: (result) => { setPublishResult(result); queryClient.invalidateQueries({ queryKey: getListAssessmentPackagePublicationHistoryQueryKey(id) }); queryClient.invalidateQueries({ queryKey: getGetAssessmentQueryKey(id) }); queryClient.invalidateQueries({ queryKey: getGetAssessmentPackageVersionQueryKey(id, version) }); queryClient.invalidateQueries({ queryKey: getListAssessmentsQueryKey() }); if (result.status === "published") toast({ title: "RoleplayX 발행 완료", description: "최신 발행 이력에서 결과를 확인하세요." }); else toast({ variant: "destructive", title: "발행 실패 — 재시도할 수 있습니다", description: result.errorCategory ?? "unknown" }); }, onError: (error) => { queryClient.invalidateQueries({ queryKey: getListAssessmentPackagePublicationHistoryQueryKey(id) }); queryClient.invalidateQueries({ queryKey: getGetAssessmentQueryKey(id) }); queryClient.invalidateQueries({ queryKey: getListAssessmentsQueryKey() }); setPublishResult({ status: "failed", errorCategory: error.message }); toast({ variant: "destructive", title: "발행 실패 — 재시도할 수 있습니다", description: error.message }); } });

  if (packageQuery.isLoading) return <Layout breadcrumbs={[{ label: "ContentX" }, { label: "Assessments", href: "/assessments" }, { label: "Loading" }]}><div className="p-12 flex justify-center"><Loader2 className="animate-spin" /></div></Layout>;
  if (!packageQuery.data) return <Layout breadcrumbs={[{ label: "ContentX" }, { label: "Assessments", href: "/assessments" }, { label: id }]}><div className="p-8 text-muted-foreground">Assessment version을 찾을 수 없습니다.</div></Layout>;
  const assessment = packageQuery.data;
  const selectedVersion = assessmentDetail.data?.versions.find((item) => item.version === version);
  const alreadyPublished = selectedVersion?.status === "published";
  const nextVersion = latestVersion + 1;
  const createNewVersion = (packageId: string, data: AssessmentPackageVersionCreateInput) => createVersion.mutate({ id: packageId, data }, {
    onSuccess: (created) => {
      queryClient.invalidateQueries({ queryKey: getListAssessmentsQueryKey() });
      queryClient.invalidateQueries({ queryKey: getGetAssessmentQueryKey(packageId) });
      queryClient.invalidateQueries({ queryKey: getGetAssessmentPackageVersionQueryKey(packageId, created.version) });
      queryClient.invalidateQueries({ queryKey: getListAssessmentPackagePublicationHistoryQueryKey(packageId) });
      setNewVersionOpen(false);
      toast({ title: "새 immutable version이 생성되었습니다", description: `v${created.version}을 검증하세요.` });
      setLocation(`/assessments/${packageId}?version=${created.version}`);
    },
    onError: (error) => toast({ variant: "destructive", title: "새 버전을 저장하지 못했습니다", description: error.message }),
  });
  return <Layout breadcrumbs={[{ label: "ContentX" }, { label: "Assessments", href: "/assessments" }, { label: assessment.metadata.title }]} title={<span className="font-mono text-sm">v{assessment.version}</span>}>
    <div className="max-w-5xl mx-auto p-4 md:p-6 space-y-5">
      {assessmentDetail.data && <div data-testid="assessment-overview" className="rounded-xl border p-3 text-sm">상태: <b>{selectedVersion?.status ?? "draft"}</b> · 최신 v{assessmentDetail.data.currentVersion} · <span className="inline-flex gap-1 ml-2">{assessmentDetail.data.versions.map((item) => <Button key={item.id} data-testid={`button-version-${item.version}`} size="sm" variant={item.version === version ? "default" : "outline"} onClick={() => setLocation(`/assessments/${id}?version=${item.version}`)}>v{item.version} · {item.status}</Button>)}</span> · RoleplayX target</div>}
      <div className="rounded-xl border bg-card p-5 flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><h1 className="text-xl font-semibold">{assessment.metadata.title}</h1><p className="text-sm text-muted-foreground mt-1">{assessment.metadata.description}</p><p data-testid="text-package-summary" className="text-xs text-muted-foreground mt-3">{assessment.metadata.locale} · {assessment.competencies.length} competencies · {assessment.scenarios.length} scenarios</p></div><div className="flex flex-wrap gap-2"><Button data-testid="button-new-assessment-version" variant="outline" onClick={() => setNewVersionOpen(true)}><PlusCircle className="h-4 w-4 mr-2" />새 버전</Button>{!alreadyPublished && <><Button data-testid="button-validate-assessment" variant="outline" onClick={runValidation} disabled={validate.isPending}>{validate.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}검증</Button><Button data-testid="button-publish-assessment" onClick={() => setPublishOpen(true)} disabled={validation !== true}> <Send className="h-4 w-4 mr-2" />RoleplayX 발행</Button></>}</div></div>
      {alreadyPublished && <div data-testid="status-assessment-immutable" className="rounded-lg border border-primary/30 bg-primary/5 p-3 text-sm">선택한 v{version}은 발행되어 immutable 상태입니다. 검증·발행·편집은 불가하지만 새 후속 버전은 만들 수 있습니다.</div>}
      {validation === false && <div data-testid="status-validation-failed" className="rounded-lg border border-destructive/50 bg-destructive/5 p-3 text-sm flex gap-2"><ShieldAlert className="h-4 w-4 text-destructive" />검증에 실패했습니다. 오류를 고친 새 immutable version을 생성하세요.</div>}
      {diagnostics.length > 0 && <ul data-testid="list-validation-diagnostics" className="rounded-lg border p-3 text-sm">{diagnostics.map((item, index) => <li key={`${item.path}-${index}`}>{item.path}: {item.message}</li>)}</ul>}
      {validation === true && <div data-testid="status-validation-passed" className="rounded-lg border border-primary/30 bg-primary/5 p-3 text-sm flex gap-2"><CheckCircle2 className="h-4 w-4 text-primary" />검증 성공. {assessment.scenarios.length} scenarios · {assessment.competencies.length} competencies · {assessment.scenarios.reduce((total, scenario) => total + scenario.evaluation.dimensions.length, 0)} evaluation dimensions</div>}
      <Tabs defaultValue="preview"><TabsList><TabsTrigger value="preview" data-testid="tab-human-preview">사람이 읽는 preview</TabsTrigger><TabsTrigger value="json" data-testid="tab-advanced-json">고급 JSON</TabsTrigger></TabsList><TabsContent value="preview" className="rounded-xl border bg-card p-5 mt-3 space-y-4">{assessment.scenarios.map((scenario) => <article key={scenario.key} className="border-b last:border-0 pb-4 last:pb-0"><div className="flex justify-between"><h2 className="font-semibold">{scenario.title}</h2><span data-testid={`status-scenario-validation-${scenario.key}`} className="text-xs text-primary">{validation === false ? "diagnostics available" : "valid"}</span></div><p className="text-sm text-muted-foreground">{scenario.description}</p><div className="grid sm:grid-cols-4 gap-3 mt-3 text-sm"><div><b>역량</b><p>{scenario.competencies.join(", ")}</p></div><div><b>Persona</b><p>{scenario.personas.map((persona) => persona.name).join(", ")}</p></div><div><b>난이도 / 시간</b><p>{scenario.difficulty} · {scenario.estimatedTime}분</p></div><div><b>평가 차원</b><p>{scenario.evaluation.dimensions.map((dimension) => dimension.label).join(", ")}</p></div></div></article>)}<details className="rounded-lg border p-3 text-xs"><summary className="cursor-pointer font-medium">고급 정보</summary><p className="mt-2 font-mono">content hash: {assessment.provenance.contentHash}</p></details></TabsContent><TabsContent value="json" className="mt-3"><pre data-testid="text-assessment-json" className="rounded-xl border bg-card p-4 max-h-[520px] overflow-auto text-xs">{JSON.stringify(assessment, null, 2)}</pre></TabsContent></Tabs>
      <section className="rounded-xl border bg-card overflow-hidden"><div className="p-4 border-b font-semibold">발행 이력 <span className="text-xs font-normal text-muted-foreground">최신순</span></div><div className="divide-y">{historyQuery.isLoading ? <div className="p-4 text-sm text-muted-foreground">이력을 불러오는 중…</div> : historyQuery.data?.length ? historyQuery.data.map((record) => <div data-testid={`row-publish-history-${record.id}`} key={record.id} className="p-4 text-sm flex justify-between gap-3"><div><b>{record.status}</b><span className="text-muted-foreground"> · {record.organizationId}/{record.category} · 시도 {record.attempt}</span>{record.errorMessage && <p className="text-destructive text-xs mt-1">{record.errorMessage}</p>}</div><time className="text-xs text-muted-foreground whitespace-nowrap">{new Date(record.createdAt).toLocaleString()}</time></div>) : <div className="p-4 text-sm text-muted-foreground">아직 발행 이력이 없습니다.</div>}</div></section>
    </div>
    <Dialog open={publishOpen} onOpenChange={setPublishOpen}><DialogContent><DialogHeader><DialogTitle>RoleplayX에 발행</DialogTitle><DialogDescription>검증된 immutable v{version}을 조직과 카테고리에 가져옵니다.</DialogDescription></DialogHeader><ol data-testid="publish-progress" className="text-xs space-y-1">{["Package preparation", "Local validation", "Target validation", "Import", "Complete"].map((step, index) => <li key={step} className={publish.isPending || publishResult?.status === "published" ? "text-primary" : "text-muted-foreground"}>{index + 1}. {step}{publish.isPending && index === 3 ? "…" : ""}</li>)}</ol><div className="space-y-3"><div className="space-y-1"><Label htmlFor="input-publish-organization">Organization ID</Label><Input id="input-publish-organization" data-testid="input-publish-organization" value={organizationId} onChange={(event) => setOrganizationId(event.target.value)} /></div><div className="space-y-1"><Label htmlFor="input-publish-category">Category</Label><Input id="input-publish-category" data-testid="input-publish-category" value={category} onChange={(event) => setCategory(event.target.value)} /></div></div>{publishResult?.status === "published" && <div data-testid="status-publish-success" className="text-sm text-primary">Import complete · {String(publishResult.response?.importedScenarioCount ?? 0)} scenarios · {typeof publishResult.response?.roleplayXUrl === "string" && <a className="underline" href={publishResult.response.roleplayXUrl}>RoleplayX에서 열기</a>}</div>}{publishResult?.status === "failed" && <div data-testid="status-publish-failed" className="text-sm text-destructive">안전하게 실패했습니다: {publishResult.errorCategory ?? "unknown"}. 아래 버튼으로 재시도하세요.</div>}<DialogFooter><Button data-testid="button-confirm-publish" onClick={runPublish} disabled={!organizationId || !category || publish.isPending}>{publish.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}{publishResult?.status === "failed" ? "발행 재시도" : "발행 시작"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={newVersionOpen} onOpenChange={setNewVersionOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>새 버전 만들기</DialogTitle><DialogDescription>최신 v{latestVersion} 내용을 바탕으로 v{nextVersion}을 생성합니다.</DialogDescription></DialogHeader><AssessmentVersionForm packageId={id} version={nextVersion} initialValues={{ title: (latestPackageQuery.data ?? assessment).metadata.title, description: (latestPackageQuery.data ?? assessment).metadata.description, competency: (latestPackageQuery.data ?? assessment).competencies[0]?.name, dimensionLabel: (latestPackageQuery.data ?? assessment).scenarios[0]?.evaluation.dimensions[0]?.label, dimensionKey: (latestPackageQuery.data ?? assessment).scenarios[0]?.evaluation.dimensions[0]?.key, criteria: (latestPackageQuery.data ?? assessment).scenarios[0]?.evaluation.dimensions[0]?.criteria.join("\n"), passingScore: String((latestPackageQuery.data ?? assessment).scenarios[0]?.evaluation.passingScore ?? 70), maxTurns: String((latestPackageQuery.data ?? assessment).scenarios[0]?.termination.maxTurns ?? 10), targetTurns: String((latestPackageQuery.data ?? assessment).scenarios[0]?.targetTurns ?? 5) }} isPending={createVersion.isPending} onSubmit={createNewVersion} /></DialogContent></Dialog>
  </Layout>;
}